name: 'reliable-changelog'
description: 'A reliable action for generating changelogs for commitlint commits.'
author: 'Travis Lane (Tormak)'
inputs:
  github-token:
    description: "Github token"
    default: ${{ github.token }}
    required: false
    
  git-message:
    description: "Commit message to use"
    default: "chore(release): {version}"
    required: false

  git-user-name:
    description: "The git user.name to use for the commit"
    default: "Reliable Changelog Action"
    required: false

  git-user-email:
    description: "The git user.email to use for the commit"
    default: "reliable.changelog.action@github.com"
    required: false

  git-pull-method:
    description: "The git pull method used when pulling all changes from remote"
    default: "--ff-only"
    required: false

  git-branch:
    description: "The git branch to push changes to"
    default: ${{ github.ref }}
    required: false

  git-url:
    description: "Git Url"
    default: "github.com"
    required: false

  tag-prefix:
    description: "Prefix to use for the new git tag"
    default: "v"
    required: false

  current-version:
    description: "The current version, or a relative path to a version file. Supported formats: \"json\", \"toml\", and \"yaml\"."
    default: "./package.json"
    required: false
  
  version-path:
    description: "Path to the version property seperated by \".\"s. (**Note:** The version should be in the form `X.X.X`)"
    default: "version"
    required: false

  strip-commit-prefix:
    description: "Whether to strip the commit prefixes (fix:, feat:, etc)"
    default: "true"
    required: false

  major-release-commit-message:
    description: "The commit message used to signify a new major release."
    default: "feat: major release"
    required: false

  included-types:
    description: "A string of comma separated commit types to include."
    default: "feat,fix,build"
    required: false

  minor-commit-types:
    description: "Comma seperated list of commit types that trigger minor version changes (0.X.0)"
    default: "feat"
    required: false

  minor-version-bump-interval:
    description: "The number of minor version commits needed to bump the version past 1 in a single release."
    default: "5"
    required: false

  patch-commit-types:
    description: "Comma seperated list of commit types that trigger patch version changes (0.0.X)"
    default: "fix,build,docs,ci,perf,refactor,revert,style,test"
    required: false

  patch-version-bump-interval:
    description: "The number of patch version commits needed to bump the version past 1 in a single release."
    default: "5"
    required: false

  feat-section-label:
    description: "The label for the feat commits section."
    default: "New Features"
    required: false

  fix-section-label:
    description: "The label for the fix commits section."
    default: "Bug Fixes"
    required: false
    
  build-section-label:
    description: "The label for the build commits section."
    default: "Build Pipeline Improvements"
    required: false
    
  docs-section-label:
    description: "The label for the docs commits section."
    default: "Documentation Changes"
    required: false
    
  ci-section-label:
    description: "The label for the ci commits section."
    default: "CI Changes"
    required: false
    
  perf-section-label:
    description: "The label for the perf commits section."
    default: "Performance Improvements"
    required: false
    
  refactor-section-label:
    description: "The label for the refactor commits section."
    default: "Refactoring"
    required: false
    
  revert-section-label:
    description: "The label for the revert commits section."
    default: "Reverted Changes"
    required: false
    
  style-section-label:
    description: "The label for the style commits section."
    default: "Styling Changes"
    required: false
    
  test-section-label:
    description: "The label for the test commits section."
    default: "Testing Changes"
    required: false
    
outputs:
  changelog:
    description: "A tidied version of the generated changelog."

  tag:
    description: "The tag for the new release."

  version:
    description: "The version for the new release."

runs:
  using: 'node16'
  main: 'dist/index.cjs'
